name: AdvancedTeleport
version: ${project.version}
main: me.TeamsInsane.AdvancedTeleport.Core
api-version: 1.17
author: TeamsInsane
commands:
  tpa:
    description: Teleports you to another player.
  tpaccept:
    description: Accept the player teleport.
  tpdeny:
    description: Denies the player teleport.
  tpconfirm:
    description: Confirms the teleportation.
  tpback:
    description: Denies the teleportation.
  tptoggle:
    description: Toggles safe teleportation.
